#ifndef REG_H
#define REG_H

#include"mem.h"
// flash controller的相关寄存器地址定义
#ifdef EMU
#define FLASH_CTL_BASE_ADDR 			(FCL_BASE)
#else
#define FLASH_CTL_BASE_ADDR 			0x60000000
#endif

//系统寄存器相关
#define FLASH_CTL_SYS_REG_BASE_ADDR		(FLASH_CTL_BASE_ADDR+0x00000000)

// 硬件通道相关
#define FLASH_CTL_CH0_REG_BASE_ADDR		(FLASH_CTL_BASE_ADDR+0x00800000)
#define FLASH_CTL_CH1_REG_BASE_ADDR		(FLASH_CTL_BASE_ADDR+0x00A00000)
#define FLASH_CTL_CH2_REG_BASE_ADDR		(FLASH_CTL_BASE_ADDR+0x00C00000)
#define FLASH_CTL_CH3_REG_BASE_ADDR		(FLASH_CTL_BASE_ADDR+0x00E00000)


#endif